services:
  - type: web
    name: ecommerce-app
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRATION
        value: 7d
      - key: JWT_COOKIE_EXPIRES
        value: 1
      - key: DATABASE_URL
        fromDatabase:
          name: ecommerce-db
          property: connectionString
      - key: MERCADOPAGO_ACCESS_TOKEN
        sync: false

databases:
  - name: ecommerce-db
    databaseName: ecommerce
    user: ecommerce_user
    plan: free
